config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'products#index'
    resources :products
    resources :genres
    resources :customers, only: [:index,:show,:edit,:update]
    resources :orders,only: [:index,:show,:edit,:update]
    resources :order_products,only: [:update]
  end

  scope module: :public do
    root 'homes#top'
    get '/about' => 'homes#about'
    get '/search' => 'searches#search'

    resource :customers,only: [:edit,:update,:show] do
      collection do
        get 'unsubscribe'
      end
      patch 'withdrawal'
    end
    resources :products, only: [:index,:show]
    resources :cart_products, only: [:index,:create,:update,:destroy] do
      collection do
        delete '/' => '/customer/cart_products#destroy_all'
      end
    end
    resources :deliveries,only: [:index,:edit,:create,:update,:destroy]
    resources :orders,only: [:index,:show,:new,:create,] do
      collection do
        get 'check'
        get 'thanks'
      end
    end
  end

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords,], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :deliveries
  has_many :cart_products
  has_many :orders

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :post_code, presence: true
  validates :address, presence: true
  validates :tel, presence: true
  validates :email, presence: true
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path
    else
      render 'edit'
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana,  :post_code, :address, :tel, :email, :withdrawal_status)
  end


end

app/controllers/customer/cart_products_controller.rb
class Customer::CartProductsController < ApplicationController


  def destroy_all
    current_customer.cart_products.destroy_all
    redirect_to cart_products_path ,notice:"削除しました"
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="l-main_container">
  <h2 class="admin-title"><%= @customer.last_name %><%= @customer.first_name %>さんの<br class="u-sp">会員情報編集</h2>
  <%= form_with model: @customer, url: admin_customer_path, local: true do |f| %>
    <table class="cutomer-edit_table">
      <tr>
        <th>会員ID</th>
        <td><%= @customer.id %></td>
      </tr>
      <tr>
        <th><%= f.label :"氏名" %></th>
        <td>
          <%= f.text_field :last_name, autofocus: true %>
          <%= f.text_field :first_name, autofocus: true %>
        </td>
      </tr>
      <tr>
        <th><%= f.label :"フリガナ" %></th>
        <td>
          <%= f.text_field :last_name_kana, autofocus: true %>
          <%= f.text_field :first_name_kana, autofocus: true %>
        </td>
      </tr>
      <tr>
        <th><%= f.label :"郵便番号" %></th>
        <td><%= f.text_field :post_code, autofocus: true %></td>
      </tr>
      <tr  class="cutomer-edit_table_address">
        <th><%= f.label :"住所"%></th>
        <td><%= f.text_field :address, autofocus: true %></td>
      </tr>
      <tr>
        <th><%= f.label :"電話番号" %></th>
        <td><%= f.telephone_field :tel, autofocus: true %></td>
      </tr>
      <tr>
        <th><%= f.label :"メールアドレス" %></th>
        <td><%= f.email_field :email, autofocus: true, autocomplete: "email" %></td>
      </tr>
      <tr>
        <th><%= f.label :"会員ステータス", class: "control-label" %></th>
        <td>
          <%= f.radio_button :withdrawal_status, :false %>
          <%= f.label :withdrawal_status, "有効", {value: :false } %>
          <%= f.radio_button :withdrawal_status, :true %>
          <%= f.label :withdrawal_status, "退会", {value: :true } %>
        </td>
      </tr>
    </table>
  <%= f.submit "変更を保存", class: "admin-customer_edit_btn" %>
  <% end %>
</main>

app/views/admin/customers/index.html.erb
<div class="l-main_container">
  <h2 class="admin-title">会員一覧</h2>
  <table class="admin-product_table">
    <tr>
      <th>会員<br class="u-sp">ID</th>
      <th>氏名</th>
      <th>メール<br class="u-sp">アドレス</th>
      <th>ステータス</th>
    </tr>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>
        <td class="admin-product_table_name">
          <%= link_to admin_customer_path(customer) do %>
          <%= customer.last_name %><br class="u-sp"><%= customer.first_name %>
          <% end %>
        </td>
        <td><%= customer.email %></td>
        <td>
          <% if customer.withdrawal_status == true%>
            <div class="text-secondary">退会</div>
          <% else %>
            <div class="text-success">有効</div>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
<%= paginate @customers %>
</div>

app/views/admin/customers/show.html.erb
<div class="l-main_container">
  <h2 class="admin-title"><%= @customer.last_name %><%= @customer.first_name %>さんの<br class=u-sp>会員詳細</h2>
  <table class="cutomer-edit_table">
    <tr>
      <th>会員</th>
      <td><%= @customer.id %></td>
    </tr>
    <tr>
      <th>氏名</th>
      <td>
        <%= @customer.last_name %>
        <%= @customer.first_name %></td>
    </tr>
    <tr>
      <th>フリガナ</th>
      <td>
        <%= @customer.last_name_kana %>
        <%= @customer.first_name_kana %>
      </td>
    </tr>
    <tr>
      <th>郵便番号</th>
      <td><%= @customer.post_code %></td>
    </tr>
    <tr>
      <th>住所</th>
      <td><%= @customer.address %></td>
    </tr>
    <tr>
      <th>電話番号</th>
      <td><%= @customer.tel %></td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td><%= @customer.email %></td>
    </tr>
    <tr>
      <th>会員ステータス</th>
      <td>
        <% if @customer.withdrawal_status == true%>
          <div class="text-secondary">退会</div>
        <% else %>
          <div class="text-success">有効</div>
        <% end %>
      </td>
    </tr>
  </table>
  <div class="cutomer-edit_subtitle">
      <td><%= link_to "編集", edit_admin_customer_path(@customer), class: "customer-edit_btn" %></td>
</div>
<div class="cutomer-edit_subtitle">
            <td><%= link_to "注文履歴一覧", admin_orders_path, class: "customer-edit_btn" %></td>
</div>
</div>