config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'products#index'
    resources :products
    resources :genres
    resources :customers, only: [:index,:show,:edit,:update]
    resources :orders,only: [:index,:show,:edit,:update]
    resources :order_products,only: [:update]
  end

  scope module: :public do
    root 'homes#top'
    get '/about' => 'homes#about'
    get '/search' => 'searches#search'

    resource :customers,only: [:edit,:update,:show] do
      collection do
        get 'unsubscribe'
      end
      patch 'withdrawal'
    end
    resources :products, only: [:index,:show]
    resources :cart_products, only: [:index,:create,:update,:destroy] do
      collection do
        delete '/' => '/customer/cart_products#destroy_all'
      end
    end
    resources :deliveries,only: [:index,:edit,:create,:update,:destroy]
    resources :orders,only: [:index,:show,:new,:create,] do
      collection do
        get 'check'
        get 'thanks'
      end
    end
  end

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords,], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_products

  validates :post_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

  enum status: {
     入金待ち:0, 入金確認:1, 発送準備中:2, 発送済み:3
  }

  enum payment_method: {
     クレジット:0, 銀行振込:1
  }


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    # @orders = Order.all
    # @orders = Order.all.order("created_at DESC")
    @orders = Order.page(params[:page]).reverse_order.order("created_at DESC")

  end

  def show
    @orders = Order.find(params[:id])
  end

  def update
    @orders = Order.find(params[:id])
    @orders.update(order_params)
    redirect_to admin_order_path(@orders.id)

    # 製作ステータスの更新
    if @orders.status == "入金確認"
      @orders.order_products.each do |order_product|
        order_product.update(production_status: 1)
      end
    end

  end

  def edit
    @customers = Customer.find(params[:id])
    @orders = @customers.orders.order("created_at DESC")
  end

  private
    def order_params
    params.require(:order).permit(:status)
    end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_order.html.erb
 <tr class="admin-orders_show_table_row">
  <th>購入者</th>
  <td><%= orders.customer.last_name %><%= orders.customer.first_name %></td>
</tr>
<tr class="admin-orders_show_table_row">
  <th>注文日</th>
  <td><%= orders.created_at.strftime('%Y/%m/%d') %></td>
</tr>
<tr class="admin-orders_show_table_row">
  <th>配送先</th>
  <td>〒<%= orders.post_code %><br><%= orders.address %><br>
      <%= orders.name %>
  </td>
</tr>
<tr class="admin-orders_show_table_row">
  <th>支払方法</th>
  <td><%= orders.payment_method %></td>
</tr>
<tr class="admin-orders_show_table_row">
  <th>注文<br class="">ステータス</th>
  <td>
    <%= form_with model: orders ,url: admin_order_path(orders.id),method: :patch ,local: true  do |f| %>
      <%= f.select :status , Order.statuses.keys.map %>
      <%= f.submit '変更', class: "admin-orders_show_customer_table_btn" %>
    <% end %>
  </td>
</tr>

app/views/admin/orders/edit.html.erb
<div class="l-main_container">
  <div class="m-page_title">
    <h2 class="admin-title">注文履歴一覧</h2>
  </div>
  <%= @customers.last_name %><%= @customers.first_name %>さんの注文
  <table class="admin-orders_table">
    <tr class="admin-orders_table_row">
      <td>購入日時</td>
      <td>注文個数</td>
      <td>注文ステータス</td>
    </tr>
    <% @orders.each do |order| %>
      <tr class="admin-orders_table_row">
        <td><%= link_to admin_order_path(order.id) do %>
          <%= order.created_at.strftime('%Y/%m/%d') %>　<%= order.created_at.strftime('%H:%M:%S') %>
          <% end %></td>
        <td><%= order.order_products.sum(:quantity) %></td>
        <td><%= order.status %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/admin/orders/index.html.erb
<div class="l-main_container">
  <div class="m-page_title">
    <h2 class="admin-title">注文履歴一覧</h2>
  </div>
  <table class="admin-orders_table">
    <tr class="admin-orders_table_row">
      <th>購入日時</th>
      <th>購入者</th>
      <th>注文<br class="u-sp">個数</th>
      <th>注文<br class="u-sp">ステータス</th>
    </tr>
    <% @orders.each do |order| %>
      <%# order.order_products.each do |item| %>
      <tr class="admin-orders_table_row">
        <td>
          <%= link_to admin_order_path(order.id) do %>
          <%= order.created_at.strftime('%Y/%m/%d') %>　<br class="u-sp"><%= order.created_at.strftime('%H:%M:%S') %>
          <% end %>
        </td>
        <td>
          <%=link_to edit_admin_order_path(order.customer.id) do %>
            <%= "#{order.customer.last_name} #{order.customer.first_name}" %>
          <% end %>
        </td>
        <td><%= order.order_products.sum(:quantity) %></td>
        <td><%= order.status %></td>
      </tr>
      <%# end %>
    <% end %>
  </table>
  <%= paginate @orders %>
</div>

app/views/admin/orders/order.js.erb
$(".admin-orders_show_table).html("<%= j(render 'admin/orders/order', { orders: @orders}) %>")

app/views/admin/orders/show.html.erb
<div class="l-main_container">
  <div class="m-page_title">
    <h2 class="admin-title">注文履歴詳細</h2>
  </div>

  <table class="admin-orders_show_table">
    <%= render 'order', orders: @orders %>
  </table>

  <div class="admin-orders_show_column">
    <table class="admin-orders_show_product_table">
      <tr class="admin-orders_show_product_table_row">
        <th>商品名</th>
        <th>単価<br>(税込)</th>
        <th>数量</th>
        <th>小計</th>
        <th>製作<br>ステータス</th>
      </tr>

      <% @orders.order_products.each do |order|%>
        <tr class="admin-orders_show_product_table_row">
          <td class="admin-orders_show_product_table_name"><%= order.product.name %></td>
          <td><%= order.product.price %></td>
          <td><%= order.quantity %></td>
          <td><%= order.product.add_tax_price.to_s(:delimited)  %></td>
          <td>
          <%= form_with model: order ,url: admin_order_product_path(order.id) ,method: :patch ,local: true  do |f| %>
          <%= f.select :production_status , OrderProduct.production_statuses.keys.map %>
          <%= f.submit '変更', class: "admin-orders_show_product_table_btn" %>
          <% end %>
          </td>
        </tr>
      <% end %>
    </table>

    <table class="admin-orders_show_price_table">
      <tr class="admin-orders_show_price_table_row">
        <th>商品合計</th>
        <td><%= @orders.total_price.to_s(:delimited)  %></td>
      </tr>
      <tr class="admin-orders_show_price_table_row">
        <th>送料</th>
        <td><%= @orders.postage.to_s(:delimited)  %></td>
      </tr>
      <tr class="admin-orders_show_price_table_row">
        <th>請求金額合計</th>
        <td><%= @orders.total_price+@orders.postage   %></td>
      </tr>
    </table>
  </div>
</div>