config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'products#index'
    resources :products
    resources :genres
    resources :customers, only: [:index,:show,:edit,:update]
    resources :orders,only: [:index,:show,:edit,:update]
    resources :order_products,only: [:update]
  end

  scope module: :public do
    root 'homes#top'
    get '/about' => 'homes#about'
    get '/search' => 'searches#search'

    resource :customers,only: [:edit,:update,:show] do
      collection do
        get 'unsubscribe'
      end
      patch 'withdrawal'
    end
    resources :products, only: [:index,:show]
    resources :cart_products, only: [:index,:create,:update,:destroy] do
      collection do
        delete '/' => '/customer/cart_products#destroy_all'
      end
    end
    resources :deliveries,only: [:index,:edit,:create,:update,:destroy]
    resources :orders,only: [:index,:show,:new,:create,] do
      collection do
        get 'check'
        get 'thanks'
      end
    end
  end

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords,], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :customer
  belongs_to :product
  
def subtotal #小計の式
    self.add_tax_price * quantity
end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :deliveries
  has_many :cart_products
  has_many :orders

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :post_code, presence: true
  validates :address, presence: true
  validates :tel, presence: true
  validates :email, presence: true
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :customer

  validates :post_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :products

  validates :name, presence:true

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_products

  validates :post_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

  enum status: {
     入金待ち:0, 入金確認:1, 発送準備中:2, 発送済み:3
  }

  enum payment_method: {
     クレジット:0, 銀行振込:1
  }


end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
    belongs_to :product
    belongs_to :order

      enum production_status: {
     着手不可:0, 製作待ち:1, 製作中:2, 製作完了:3
  }

end

app/models/product.rb
class Product < ApplicationRecord

  belongs_to :genre
  has_many :cart_products, dependent: :destroy
  has_many :order_products

  attachment :image

  validates :genre_id, presence:true
  validates :name, presence:true
  validates :description, presence:true
  validates :image, presence:true
  validates :price, presence:true

  def add_tax_price
    (self.price * 1.10).round
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(params_genre)
    if @genre.save
      redirect_to request.referer, notice: "登録しました"
    else
      @genre = Genre.new
      @genres = Genre.all
    end
  end

  def edit
    @genre = Genre.find(params[:id])

  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(params_genre)
      redirect_to admin_genres_path(@genre), notice: "登録しました"
    else
      render 'edit'
    end
  end

  private

  def params_genre
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    # @orders = Order.all
    # @orders = Order.all.order("created_at DESC")
    @orders = Order.page(params[:page]).reverse_order.order("created_at DESC")

  end

  def show
    @orders = Order.find(params[:id])
  end

  def update
    @orders = Order.find(params[:id])
    @orders.update(order_params)
    redirect_to admin_order_path(@orders.id)

    # 製作ステータスの更新
    if @orders.status == "入金確認"
      @orders.order_products.each do |order_product|
        order_product.update(production_status: 1)
      end
    end

  end

  def edit
    @customers = Customer.find(params[:id])
    @orders = @customers.orders.order("created_at DESC")
  end

  private
    def order_params
    params.require(:order).permit(:status)
    end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @product = Product.new
    @genres = Genre.all
    @action = "new"
  end

  def index
    @products = Product.all.page(params[:page]).per(10)
  end

  def create
    @product = Product.new(params_product)
    if @product.save
      redirect_to admin_product_path(@product), notice: "登録しました"
    else
      @action = "new"
      render 'new'
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @genres = Genre.all
    @product = Product.find(params[:id])
    @action = "edit"
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(params_product)
      redirect_to admin_product_path(@product), notice: "変更しました"
    else
      render 'edit'
    end
  end

  private

  def params_product
    params.require(:product).permit(:id, :genre_id, :name, :description, :image, :price, :sale_status)
  end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if resource.is_a?(Admin)
      admin_orders_path
    else
      root_path
    end
  end

  def after_sign_out_path_for(resource)
    if resource == :admin
      new_admin_session_path
    else
      root_path
    end
  end

 protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :post_code, :address, :tel, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/order_products_helper.rb
module Admin::OrderProductsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cutomer/cart_products_helper.rb
module Cutomer::CartProductsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/genres/_genre_list.html.erb
<% @genres.each do |genre| %>
  <tr>
    <th><%= genre.name %></th>
    <td><%= link_to '編集する', edit_admin_genre_path(genre), class: "ganre-index_list_table_btn" %></td>
  </tr>
<% end %>

app/views/admin/genres/edit.html.erb
<div class="l-main_container">
  <h2 class="admin-title">ジャンル編集</h2>
  <%= form_with model: [:admin, @genre], local: true do |f| %>
  <table class="ganre-index_form_table">
    <tr>
      <td><%= f.label :ジャンル名 %></td>
      <td><%= f.text_field :name %></td>
      <td><%= f.submit '変更を保存',class: "ganre-edit_form_table_btn" %></td>
    </tr>
  </table>
<% end %>
</div>

app/views/admin/genres/index.html.erb
<div class="l-main_container">
  <h2 class="ganre-title">ジャンル一覧・追加</h2>
  <%= form_with model: [:admin, @genre], remote: true do |f| %>
    <table class="ganre-index_form_table">
      <tr>
          <td><%= f.label :ジャンル名 %></td>
          <td><%= f.text_field :name %></td>
          <td><%= f.submit '新規登録',class: "ganre-index_form_table_btn" %></td>
      </tr>
    </table>
  <% end %>
  <table class="ganre-index_list_table">
    <tr>
      <th>ジャンル</th>
    </tr>
    <div id="genre_list">
      <%= render 'genre_list', genres: @genres %>
    </div>
  </table>
</div>

app/views/admin/genres/index.js.erb
$('#genre_list').html("<%= j(render partial: 'admin/genres/genre_list', locals: {genres: @genres}) %>");

app/views/admin/products/_form.html.erb
<%= form_with model: [:admin, product], local: true do |f| %>
  <table class="admin-product_new_table">
    <tr>
      <th><%= f.label :"商品画像"%></th>
      <td><%= f.attachment_field :image %></td>
    </tr>
    <tr>
      <th><%= f.label :"商品名" %></th>
      <td><%= f.text_field :name, :placeholder => "商品名"%></td>
    </tr>
    <tr>
      <th><%= f.label :"商品説明"%></th>
      <td><%= f.text_area :description, :placeholder => "ここに説明文を記述します" %></td>
    </tr>
    <tr>
      <th><%= f.label :"ジャンル" %></th>
      <td><%= f.collection_select :genre_id, Genre.all, :id, :name, :prompt => "--選択してください--" %></td>
    </tr>
    <tr>
      <th><%= f.label :"税込価格"%></th>
      <td><%= f.text_field :price, :placeholder => "1000"%></td>
    </tr>
    <tr>
      <th><%= f.label :販売ステータス %></th>
      <td class="admin-product_new_radio">
        <%= f.radio_button :sale_status, :true, checked: true %>
        <%= f.label "販売中" %>
        <%= f.radio_button :sale_status, :false %>
        <%= f.label "販売停止中" %>
      </td>
    </tr>
  </table>
  <% if @action == "new" %>
    <%= f.submit "新規登録", class: "admin-product_new_btn" %>
  <% else %>
    <%= f.submit "変更を保存", class: "admin-product_new_btn" %>
  <% end %>
<% end%>

app/views/admin/products/edit.html.erb
<div class="l-main_container">
  <h2 class="admin-title">商品編集</h2>
    <%= render 'form', product: @product, genres: @genres %>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="l-main_container">
  <div class="m-page_title">
    <h2 class="admin-title">商品一覧</h2>
    <%= link_to new_admin_product_path, class: 'admin-product_plus' do %>
    <% end %>
  </div>
  <table class="admin-product_table">
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜<br class="u-sp">価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
      <% @products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= link_to product.name, admin_product_path(product) %></td>
        <td><%= product.price %></td>
        <td><%= product.genre.name %></td>
        <td>
          <% if product.sale_status %>
            <div class="text-success">販売中</div>
          <% else %>
            <div class="text-secondary">販売<br class="u-sp">停止中</div>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= paginate @products %>
</div>

app/views/admin/products/new.html.erb
<div class="l-main_container">
  <h2 class="admin-title">商品新規登録</h2>
    <%= render 'form', product: Product.new, genres: @genres %>
  </div>
</div>

app/views/admin/products/show.html.erb
<div class="l-main_container">
  <h2 class="admin-title">商品詳細</h2>
  <div class="admin-product_show_container">
    <div class=""><%= attachment_image_tag(@product, :image, size: "300x217") %></div>
    <div class="admin-product_show_product">
      <table class="admin-product_show_product_table">
        <tr>
          <th>商品名</th>
          <td><%= @product.name %></td>
        </tr>
        <tr>
          <th>商品説明</th>
          <td><%= @product.description %></td>
        </tr>
        <tr>
          <th>ジャンル</th>
          <td><%= @product.genre.name %></td>
        </tr>
        <tr>
          <th>税込価格<br class="u-pc">(税抜価格)</th>
          <td><%= "#{@product.add_tax_price.to_s(:delimited, delimiter:',')} (#{@product.price.to_s(:delimited, delimiter:',')}) 円" %></td>
        </tr>
        <tr>
          <th>販売ステータス</th>
          <td>
            <% if @product.sale_status %>
              <div class="text-success">販売中</div>
            <% else %>
              <div class="text-secondary">販売停止中</div>
            <% end %>
          </td>
        </tr>
      </table>
      <%= link_to '編集する', edit_admin_product_path(@product), class: "admin-product_show_product_btn" %>
    </div>
  </div>
</div>