config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'products#index'
    resources :products
    resources :genres
    resources :customers, only: [:index,:show,:edit,:update]
    resources :orders,only: [:index,:show,:edit,:update]
    resources :order_products,only: [:update]
  end

  scope module: :public do
    root 'homes#top'
    get '/about' => 'homes#about'
    get '/search' => 'searches#search'

    resource :customers,only: [:edit,:update,:show] do
      collection do
        get 'unsubscribe'
      end
      patch 'withdrawal'
    end
    resources :products, only: [:index,:show]
    resources :cart_products, only: [:index,:create,:update,:destroy] do
      collection do
        delete '/' => '/customer/cart_products#destroy_all'
      end
    end
    resources :deliveries,only: [:index,:edit,:create,:update,:destroy]
    resources :orders,only: [:index,:show,:new,:create,] do
      collection do
        get 'check'
        get 'thanks'
      end
    end
  end

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords,], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :customer
  belongs_to :product
  
def subtotal #小計の式
    self.add_tax_price * quantity
end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :deliveries
  has_many :cart_products
  has_many :orders

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :post_code, presence: true
  validates :address, presence: true
  validates :tel, presence: true
  validates :email, presence: true
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :customer

  validates :post_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :products

  validates :name, presence:true

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_products

  validates :post_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

  enum status: {
     入金待ち:0, 入金確認:1, 発送準備中:2, 発送済み:3
  }

  enum payment_method: {
     クレジット:0, 銀行振込:1
  }


end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
    belongs_to :product
    belongs_to :order

      enum production_status: {
     着手不可:0, 製作待ち:1, 製作中:2, 製作完了:3
  }

end

app/models/product.rb
class Product < ApplicationRecord

  belongs_to :genre
  has_many :cart_products, dependent: :destroy
  has_many :order_products

  attachment :image

  validates :genre_id, presence:true
  validates :name, presence:true
  validates :description, presence:true
  validates :image, presence:true
  validates :price, presence:true

  def add_tax_price
    (self.price * 1.10).round
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(params_genre)
    if @genre.save
      redirect_to request.referer, notice: "登録しました"
    else
      @genre = Genre.new
      @genres = Genre.all
    end
  end

  def edit
    @genre = Genre.find(params[:id])

  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(params_genre)
      redirect_to admin_genres_path(@genre), notice: "登録しました"
    else
      render 'edit'
    end
  end

  private

  def params_genre
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    # @orders = Order.all
    # @orders = Order.all.order("created_at DESC")
    @orders = Order.page(params[:page]).reverse_order.order("created_at DESC")

  end

  def show
    @orders = Order.find(params[:id])
  end

  def update
    @orders = Order.find(params[:id])
    @orders.update(order_params)
    redirect_to admin_order_path(@orders.id)

    # 製作ステータスの更新
    if @orders.status == "入金確認"
      @orders.order_products.each do |order_product|
        order_product.update(production_status: 1)
      end
    end

  end

  def edit
    @customers = Customer.find(params[:id])
    @orders = @customers.orders.order("created_at DESC")
  end

  private
    def order_params
    params.require(:order).permit(:status)
    end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if resource.is_a?(Admin)
      admin_orders_path
    else
      root_path
    end
  end

  def after_sign_out_path_for(resource)
    if resource == :admin
      new_admin_session_path
    else
      root_path
    end
  end

 protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :post_code, :address, :tel, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/order_products_helper.rb
module Admin::OrderProductsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "件") %> の入力ミスがあります。</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
    <footer class="l-footer">
      <small class="l-footer_copy">©︎Carbonara</small>
    </footer>
    <div class="top-btn">
      <i class="top-btn_text fas fa-angle-double-up"></i>
    </div>

app/views/layouts/_header.html.erb
    <header class="l-header">
      <% if admin_signed_in? %>
      <%= link_to admin_root_path do %>
      <h1 class="l-header_title"><%= image_tag('logo.png') %></h1>
      <% end %>
      <% else %>
        <%= link_to root_path do %>
      <h1 class="l-header_title"><%= image_tag('logo.png') %></h1>
      <% end %>
      <% end %>
      <nav>
        <span class="l-nav_btn">
          <span class="l-nav_btn_bar"></span>
          <span class="l-nav_btn_bar"></span>
          <span class="l-nav_btn_bar"></span>
        </span>
        <div class="l-nav">
          <ul class="l-navbarnav_list">
            <% if customer_signed_in? %>
            <li class="l-nav_item active">
              <%= link_to 'Mypage', customers_path, class: "l-nav_item_anchor"%>
            </li>
            <li class="l-nav_item active">
              <%= link_to 'Items', products_path, class: "l-nav_item_anchor"%>
            </li>
            <li class="l-nav_item active">
              <%= link_to 'Cart', cart_products_path, class: "l-nav_item_anchor"%>
            </li>
            <li class="l-nav_item">
              <%= link_to 'Log out', destroy_customer_session_path, method: :delete , class: "l-nav_item_anchor"%>
            </li>
            <% elsif admin_signed_in? %>
            <li class="l-nav_item active">
              <%= link_to 'Items', admin_products_path, class: "l-nav_item_anchor"%>
            </li>
            <li class="l-nav_item">
              <%= link_to 'Customers', admin_customers_path, class: "l-nav_item_anchor"%>
            </li>
            <li class="l-nav_item">
              <%= link_to 'Orders', admin_orders_path, class: "l-nav_item_anchor"%>
            <li class="l-nav_item">
              <%= link_to 'Genre', admin_genres_path, class: "l-nav_item_anchor", "data-turbolinks": false %>
            </li>
            </li>
            <li class="l-nav_item">
              <%= link_to 'Log out', destroy_admin_session_path, method: :delete , class: "l-nav_item_anchor"%>
            </li>
            <% else %>
            <li class="l-nav_item active">
              <%= link_to 'About', about_path, class: "l-nav_item_anchor"%>
            </li>
            <li class="l-nav_item">
              <%= link_to 'Items', products_path, class: "l-nav_item_anchor"%>
            </li>
            <li class="l-nav_item">
              <%= link_to 'Sign in','/customers/sign_up ', class: 'l-nav_item_anchor' %>
            </li>
            <li class="l-nav_item">
              <%=link_to "Log in" , new_customer_session_path, class: "l-nav_item_anchor" %>
            </li>
              <% end%>

          </ul>
          <div class="l-nav_item_other">
         <% if customer_signed_in? %>
           <span class="l-nav_item_other_name u-pc">
            ようこそ<%= current_customer.last_name %><%= current_customer.first_name %>さん！
            </span>
          <% end %>
          </div>
        </div>
      </nav>
    </header>

app/views/layouts/_login_errors.html.erb
<% flash.each do |msg_type, msg| %>
  <div class="alert alert-<%= msg_type %>" role="alert" id="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcSite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main class="l-main">
    <%= yield %>
    </main>
    <%= render 'layouts/footer' %>

    <script>
      $(function () {
        $('.l-nav_btn').on('click', function () {
        $('.l-nav_btn_bar').toggleClass('open');
      })
        $('.l-nav_btn').on('click', function () {
        $('.l-nav').toggleClass('show');
      })

        $('.top-btn').on('click', function () {
        let header = $('body').offset().top;
        $('html,body').animate({ scrollTop: header });
      })
        let topBtn = $('.top-btn');
        topBtn.hide();
        $(window).scroll(function () {
        if ($(this).scrollTop() > 500) {
          topBtn.fadeIn();
        } else {
          topBtn.fadeOut();
        } return false;
      });

      media();
      $(window).on("resize", function () { media(); });
      let url = location.href;
      function media() {
        let width = $(window).width();
        if (width > 771) {
          let beforePos = 0;//スクロールの値の比較用の設定

      //スクロール途中でヘッダーが消え、上にスクロールすると復活する設定を関数にまとめる
          function ScrollAnime() {
            let scroll = $(window).scrollTop();
            let nav_height = $(".l-header").outerHeight();
            //ヘッダーの出し入れをする
            // $("html").css("padding-top", nav_height);

        if (scroll < 1) {
          //ヘッダーが一番上の時
          $('.l-header').removeClass('DownMove');//.l-headerにDownMoveというクラス名を除き
          $('.l-header').removeClass('UpMove');//.l-headerにDownMoveというクラス名を除き
          $('.l-header').addClass('inv');
        } else if (0 < scroll - beforePos) {
          //下にスクロールした時ヘッダーが上に消える
          $('.l-header').removeClass('DownMove');//.l-headerにDownMoveというクラス名を除き
          $('.l-header').addClass('UpMove');//.l-headerにUpMoveのクラス名を追加

        } else {
          // 上にスクロールした時ヘッダーが上から出現
          $('.l-header').removeClass('UpMove'); //.l-headerにUpMoveというクラス名を除き
          $('.l-header').addClass('DownMove');//.l-headerにDownMoveのクラス名を追加
          $('.l-header').removeClass('inv');
        }

          beforePos = scroll;//現在のスクロール値を比較用のbeforePosに格納
        }
      // 画面をスクロールをしたら動かしたい場合の記述
          $(window).scroll(function () {
            ScrollAnime();//スクロール途中でヘッダーが消え、上にスクロールすると復活する関数を呼ぶ
          });

          // ページが読み込まれたらすぐに動かしたい場合の記述
          $(window).on('load', function () {
            ScrollAnime();//スクロール途中でヘッダーが消え、上にスクロールすると復活する関数を呼ぶ
          });

        } else if (width <= 770) {
          $('.l-header').removeClass('inv');
          let beforePos = 0;//スクロールの値の比較用の設定

          //スクロール途中でヘッダーが消え、上にスクロールすると復活する設定を関数にまとめる
          function ScrollAnime() {
            let scroll = $(window).scrollTop();
            let a = $('.l-header').outerHeight()
            let nav_height = $(".l-header").outerHeight();

          if (scroll < a) {
            $('.l-header').removeClass('inv');
            $('.l-header').removeClass('DownMove');//.l-headerにDownMoveというクラス名を除き
            $('.l-header').removeClass('UpMove');//.l-headerにDownMoveというクラス名を除き
            //IE11対策で処理を入れない
          } else if (0 < scroll - beforePos) {
              //下にスクロールした時ヘッダーが上に消える
              $('.l-header').removeClass('DownMove');//.l-headerにDownMoveというクラス名を除き
              $('.l-header').addClass('UpMove');//.l-headerにUpMoveのクラス名を追加
          } else {
             // 上にスクロールした時ヘッダーが上から出現
             $('.l-header').removeClass('UpMove'); //.l-headerにUpMoveというクラス名を除き
             $('.l-header').addClass('DownMove');//.l-headerにDownMoveのクラス名を追加
             $('.l-header').removeClass('inv');
          }

            beforePos = scroll;//現在のスクロール値を比較用のbeforePosに格納
          };
          // 画面をスクロールをしたら動かしたい場合の記述
          $(window).scroll(function () {
            ScrollAnime();//スクロール途中でヘッダーが消え、上にスクロールすると復活する関数を呼ぶ
          });

          // ページが読み込まれたらすぐに動かしたい場合の記述
          $(window).on('load', function () {
            ScrollAnime();//スクロール途中でヘッダーが消え、上にスクロールすると復活する関数を呼ぶ
          });
        };
      };

        $('.top-visual').slick({
          autoplay: true,
          autoplaySpeed: 1900,
          fade : true,
        });

        let $grid = $('.product_list'),
          emptyCells = [],
          i;

        for (i = 0; i < $grid.find('.product_list_item').length; i++) {
          emptyCells.push($('<li>', { class: 'product_list_item is-empty' }));
        }
          $grid.append(emptyCells);
      });

    </script>
  </body>

</html>